In [2]:
import numpy as np
import pandas as pd
df = pd.read_csv(r"C:\Users\msi-1\Downloads\train_and_test2.csv")
print(df)

      Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0
1               2  38.0   71.2833    1      1     0       0       0       0
2               3  26.0    7.9250    1      0     0       0       0       0
3               4  35.0   53.1000    1      1     0       0       0       0
4               5  35.0    8.0500    0      0     0       0       0       0
...           ...   ...       ...  ...    ...   ...     ...     ...     ...
1304         1305  28.0    8.0500    0      0     0       0       0       0
1305         1306  39.0  108.9000    1      0     0       0       0       0
1306         1307  38.5    7.2500    0      0     0       0       0       0
1307         1308  28.0    8.0500    0      0     0       0       0       0
1308         1309  28.0   22.3583    0      1     0       0       0       0

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0
1          0  ...        0        0        0       1        0        0
2          0  ...        0        0        0       3        0        0
3          0  ...        0        0        0       1        0        0
4          0  ...        0        0        0       3        0        0
...      ...  ...      ...      ...      ...     ...      ...      ...
1304       0  ...        0        0        0       3        0        0
1305       0  ...        0        0        0       1        0        0
1306       0  ...        0        0        0       3        0        0
1307       0  ...        0        0        0       3        0        0
1308       0  ...        0        0        0       3        0        0

      Embarked  zero.17  zero.18  2urvived
0          2.0        0        0         0
1          0.0        0        0         1
2          2.0        0        0         1
3          2.0        0        0         1
4          2.0        0        0         0
...        ...      ...      ...       ...
1304       2.0        0        0         0
1305       0.0        0        0         0
1306       2.0        0        0         0
1307       2.0        0        0         0
1308       0.0        0        0         0

[1309 rows x 28 columns]

In [2]:
 df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Passengerid  1309 non-null   int64
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64
 4   sibsp        1309 non-null   int64
 5   zero         1309 non-null   int64
 6   zero.1       1309 non-null   int64
 7   zero.2       1309 non-null   int64
 8   zero.3       1309 non-null   int64
 9   zero.4       1309 non-null   int64
 10  zero.5       1309 non-null   int64
 11  zero.6       1309 non-null   int64
 12  Parch        1309 non-null   int64
 13  zero.7       1309 non-null   int64
 14  zero.8       1309 non-null   int64
 15  zero.9       1309 non-null   int64
 16  zero.10      1309 non-null   int64
 17  zero.11      1309 non-null   int64
 18  zero.12      1309 non-null   int64
 19  zero.13      1309 non-null   int64
 20  zero.14      1309 non-null   int64
 21  Pclass       1309 non-null   int64
 22  zero.15      1309 non-null   int64
 23  zero.16      1309 non-null   int64
 24  Embarked     1307 non-null   float64
 25  zero.17      1309 non-null   int64
 26  zero.18      1309 non-null   int64
 27  2urvived     1309 non-null   int64
dtypes: float64(3), int64(25)
memory usage: 286.5 KB

In [3]:
df.shape

(1309, 28)

NameError: name 'df5' is not defined

In [5]:
(df['sub-category'].value_counts()).sort_values(ascending=false)

KeyError: 'sub-category'

In [8]:
df.sort_values('Embarked')

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
1255,1256,25.0,55.4417,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
34,35,28.0,82.1708,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
31,32,28.0,146.5208,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
30,31,40.0,27.7208,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
26,27,28.0,7.2250,0,0,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
61,62,38.0,80.0000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,NaN,0,0,1
829,830,62.0,80.0000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,NaN,0,0,1

In [5]:
df.drop_duplicates(subset=['Embarked'])

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
5,6,28.0,8.4583,0,0,0,0,0,0,0,...,0,0,0,3,0,0,1.0,0,0,0
61,62,38.0,80.0000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,NaN,0,0,1